version: "3"
services:

    nginx:
        image: nginx:stable-alpine
        container_name: laravel-kogti-php-nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    mysql:
        image: percona
        restart: always
        container_name: laravel-kogti-php-mysql
        ports:
            - 3307:3306
        command: --max_allowed_packet=16M
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'

    php:
        container_name: laravel-kogti-php
        build: docker/php
        links:
            - mysql
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
